name: image-signed-ghat-docker(latest)
on:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      id-token: write
      packages: write
      contents: write

    steps:
      - name: Checkout repository
        uses: actions/checkout@f43a0e5ff2bd294095638e18286ca9a3d1956744

      - name: Log into docker.io
        uses: docker/login-action@28218f9b04b4f3f62068d7b6ce6ca5b26e35336c
        with:
          registry: docker.io
          username: ${{ vars.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Build and push image
        id: push-step
        uses: docker/build-push-action@ac9327eae2b366085ac7f6a2d02df8aa8ead720a
        with:
          push: true
          tags: docker.io/${{ github.repository }}:latest
          context: .

      - name: Attest image
        uses: actions/attest-build-provenance@v1.0.0
        with:
          subject-name: docker.io/${{ github.repository }}
          subject-digest: ${{ steps.push-step.outputs.digest }}
